### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by rmanl** [EmergentMind/nix-config#10]
Thanks for your config, been real helpful for me especially the script and secrets part.

Have you tried setting the following under 'exec-once' in your Hyprland config?

`# set cursor for HL itself
"hyprctl setcursor ${pointer.name} ${toString pointer.size}" `

Edit: forgot I set a variable for pointer

`let
  pointer = config.home.pointerCursor;
in `

**Comment by EmergentMind** [comment]
Thanks for the suggestion. Unfortunately no change.  I really appreciate you taking the time and am glad your finding my work helpful!

I'll be putting out a new video soon, if you watch those.
