### ISSUE TITLE
README Secrets Management link broken

### ISSUE THREAD

**Issue by Serrindipity** [EmergentMind/nix-config#12]
As title says. 

> [NixOS Secrets Management](https://unmovedcentre.com/technology/2024/03/22/secrets-management.html)

should be [NixOS Secrets Management](https://unmovedcentre.com/posts/secrets-management/)

**Comment by EmergentMind** [comment]
Thank you for mentioning this, much appreciated.

Resolved in commit [3008b863a2fd7a64448c96a53f4c2e3ee7b845c2](https://github.com/EmergentMind/nix-config/commit/3008b863a2fd7a64448c96a53f4c2e3ee7b845c2)
