### ISSUE TITLE
Rename `hosts/users/ta` Directory to Use a User-Agnostic Name?

### ISSUE THREAD

**Issue by DrymarchonShaun** [EmergentMind/nix-config#18]
*Making an issue for this doesn't feel right, but making a PR seemed kinda ridiculous for what amounts to a cosmetic change*

It just occurred to me as I was starting to look at refactoring my fork to use `hostSpec` that it might make more sense if https://github.com/EmergentMind/nix-config/tree/dev/hosts/common/users/ta is renamed to something like `owner` or something to make it more obvious that it is user-agnostic (and make configuring the root user there make more sense)?

**Comment by EmergentMind** [comment]
I like it. Let's go with "primary" since that term is already used a little bit in core.

I'll push something this morning unless I run into trouble.

**Comment by EmergentMind** [comment]
Completed with e198405

Good luck on the refactor btw. The infinite recursion stuff can be annoying to debug!

**Comment by DrymarchonShaun** [comment]
> Good luck on the refactor btw. The infinite recursion stuff can be annoying to debug!

Yeah, I had looked into changing over `configVars` to use options on my own, and it took me a few days of staring at unintelligible recursion errors to give up and ask for help on the NixOS discord, where I was informed you couldn't use the values of options in imports. In hindsight, it makes sense, but it's annoying and the error messages really don't help.
