### ISSUE TITLE
Suggestion: Improve Boot Process by Using Any Linux System

### ISSUE THREAD

**Issue by jiaqiwang969** [EmergentMind/nix-config#4]
Description:
Hi sir,

I would like to suggest an improvement to the boot process. It would be better to boot from any Linux system, such as Ubuntu. This method can significantly simplify and speed up the installation process.

For instance, the NixOS-anywhere installation can be completed in about 10 minutes, as demonstrated in this [example](https://seanrmurphy.medium.com/bringing-up-a-nixos-vm-in-10-minutes-using-nixos-anywhere-6590b49ad146).

Implementing a similar approach could enhance user experience and reduce installation time.

Thank you for considering this suggestion!

**Comment by EmergentMind** [comment]
Hi, thanks for the suggestion. My use case requirements are more complex than the example because of nix-secrets being hosted in a private repo.
I would still like to improve the install speed however, so will keep this in mind when I revisit.
Thanks
