### ISSUE TITLE
Correct branch for inputs.nixpkgs?

### ISSUE THREAD

**Issue by DrymarchonShaun** [EmergentMind/nix-config#7]
I don't know if you are aware of this and have done it intentionally, (if so this issue can just be closed) but the nixpkgs input is currently using `release-24.05` which is one of the branches where pull requests get merged so that hydra builds them the next time its triggered. This means that there are often new changes in `release-24.05` that have yet to be built and cached, and as a result, when running `just rebuild-update` there are usually things that must be built locally. This isn't much of an issue if it's just a single program that updated and now requires a local build, but can quickly bloat rebuild times if something like `glib` has an update sitting in `release-24.05` waiting for hydra to build and cache. (Had this happen and ended up with most of the programs I use trying to build locally.)

If this isn't intended, best I can tell the correct branch would either be `nixpkgs-24.05` or `nixos-24.05`, depending on if you plan to mess with Darwin, or stick strictly to NixOS

See -
 [CONTRIBUTING.md#Flow of merged pull requests](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#flow-of-merged-pull-requests)
[discourse.nixos.org](https://discourse.nixos.org/t/differences-between-nix-channels/13998/5)

**Comment by EmergentMind** [comment]
This is good to know for sure. Those bloated rebuilds are brutal for some packages. As mentioned in my reply to your PR, I'm behind on working with my config, so may be a few days before I update.
Will keep this issue open until I do though. Thanks again, Appreciate it!

**Comment by EmergentMind** [comment]
Corrected the branch. Thanks again.
